Get-AppxPackage -AllUsers Microsoft.windowscommunicationsapps | Remove-AppxPackage
Get-AppxPackage -AllUsers *OneCalendar* | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.BingFoodAndDrink | Remove-AppxPackage
Get-AppxPackage -AllUsers *Skype* | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.WindowsZuneMusic | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.ZuneMusic | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.BingHealthAndFitness | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.WindowsMaps | Remove-AppxPackage
Get-AppxPackage -AllUsers *messaging* | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.MicrosoftSolitaireCollection | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.BingFinance | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.WindowsZuneVideo | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.ZuneVideo | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.BingNews | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.OneConnect | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.People | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.WindowsPhone | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.BingSports | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.Office.Sway | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.BingTravel | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.SoundRecorder | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.BingWeather | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.XboxApp | Remove-AppxPackage
Get-AppxPackage -AllUsers *CandyCrush* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Facebook* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Plex* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Spotify* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Twitter* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Viber* | Remove-AppxPackage